Create a simplified kepler API.
spruceid/kepler-sdk pull request #35
Opened 2022-03-14 14:40 UTC by cobward

Based on the API described [here](https://docs.google.com/document/d/1s0UEUBcncwjSCDsfga5Kn2nNEpgMqQqI4M5SFGv8joo).

Todo:
- [x] Currently creates a new orbit each time. Once the orbit URI work is complete we can deterministically generate the orbit id and therefore will be able to connect to the same orbit from different dapps without needing to store anything client-side.
- [x] ~Discuss and come up with appropriate types for the response from the orbit methods (or is the fetch Response type sufficient?)~ ~Sam agreed on slack that the fetch Response is appropriate, and I believe Kelsey and Charles previously agreed on this type too.~ See new design in the proposal above.
- [x] Refactor the codebase so that this is the only way to use the sdk. This can be done once the orbit URI and capability changes are done.

2022-03-15 11:40 UTC, chunningham commented
it makes sense, no semantic or logical reason the peer permission can't be delegated alongside read and write

2022-03-31 11:52 UTC, cobward commented
> it makes sense, no semantic or logical reason the peer permission can't be delegated alongside read and write

FYI - when trying to do this I couldn't work out how to construct the invocation to contain the generated peer ID. In the SIWE authn, the peer id is stored in the URI field, but I couldn't work out what the analogue for that is in the zcap authn.

2022-03-31 12:05 UTC, chunningham commented
bit of misleading code there, that message is actually a delegation, so the URI is the delegate/peer. in the zcap delegation the equivalent is `invoker` (but [might soon change to `controller`](https://github.com/w3c-ccg/zcap-spec/issues/39))

2022-03-31 12:20 UTC, chunningham requested changes
Looks good to me, although I would recommend we don't restrict the mime types when `put`ting, as I think there's no reason we should prevent users from uploading any type they want and it doesn't make it easier to use. I much enjoyed seeing how much cleaner index.ts and other stuff is though

2022-03-31 12:20 UTC, chunningham commented on src/util.ts
> +}
at this point I think we can remove this enum

2022-03-31 12:20 UTC, chunningham commented on src/index.test.ts
> +        fail('function should fail due to unsupported mime-type');
why do we want to restrict the mime types?

2022-03-31 16:58 UTC, cobward commented on src/kepler.ts
> +    async orbit(): Promise<Orbit> {
Yeah in the future that would be a parameter in `ConnectionOptions`. I think for now we should avoid the complexity of supporting that as we would probably want to use DIDs as a common interface over key types.

2022-03-31 17:00 UTC, cobward commented on src/orbit.ts
> +                streamBody ? response.body : await response.json();
That's a good question. I was working under the assumption that Kepler always returns a JSON-deserialisable list of keys as text.

2022-03-31 17:05 UTC, cobward commented on src/kepler.ts
> +type DefiniteConfig = { hosts: string[] };
Required is really nice, thanks!

For the request and response, I was thinking we should reduce the API surface by having a single type for each since there are (and we will continue to add) properties/options that are common to all functions. My plan was to describe specifically in the documentation what you can expect the functions to accept and return.

2022-03-31 17:08 UTC, cobward commented on src/index.test.ts
> +        fail('function should fail due to unsupported mime-type');
This only restricts mime-types of non-Blob objects. So if I try to put a string or an object as `application/pdf`, that will fail because the SDK does not know how to construct a Blob of that type from that input. Instead the user should construct that Blob themselves -- mime-type is only checked if the value is not a Blob.

2022-03-31 17:30 UTC, cobward commented
> I would recommend we don't restrict the mime types when putting, as I think there's no reason we should prevent users from uploading any type they want and it doesn't make it easier to use.

Spoke about this in the Kepler meeting. To clarify, the put function doesn't restrict mime types, it just only knows how to construct blobs for certain types:

* If you do `orbit.put(key, value, { type: "text/<text-type>"})`, then the sdk will store a `new Blob([value], {type: 'text/<text-type>'})`.
* If you do `orbit.put(key, value, { type: "application/json"})`, then the sdk will store a `new Blob([JSON.serialize(value)], {type: 'application/json'}`.
* If you do `orbit.put(key, value)`, and `value.constructor.name === 'Blob'`, then the sdk will just store that blob.
* Otherwise the sdk will error as it does not understand how to store the value you have provided.

This gives us the flexibility to support other types directly in the future, but for now users would need to construct a Blob themselves if they want to store something that isn't text or json.

The alternative would be providing 3 put functions, one for each of `text`, `object` and `Blob`. IMO this would make the code simpler and more obvious at the expense of a slightly broader API, so if there is an appetite for that I would happily switch. Opinions? @wyc @skgbafa @chunningham

2022-03-31 17:51 UTC, cobward commented
For @skgbafa and anyone else who wants to test this, this branch is currently dependent on the fat_packaged version of didkit, which can be built by running this script:
https://github.com/spruceid/didkit/blob/feat/fat_bundle/lib/web/fat_bundle.sh

2022-04-01 14:19 UTC, chunningham approved these changes
mis-read the `put` mime-type logic, LGTM

2022-04-06 11:55 UTC, cobward commented
After more testing and discussions with Simon, we decided the best option would be to vendor the didkit fat pkg here until we figure out and resolve the async import issue.

2022-04-07 14:24 UTC, skgbafa reviewed
- Overall the PR looks great! Love the tsdoc. Only reviewed code, did not execute functions.
- Some small js/stucture feedback
	- Do we see more changes possible for config stuff? If so, setting up a global config pattern could be good. Not worth doing if we don't see much change 
		- `invHeaderStr`
		- `"https://kepler.test.spruceid.xyz:443"`
	- Add a linter? Maybe later. For collaboration reasons.
	- Add .nvmrc. For collaboration reasons.
- Deploy the docs to gh pages? Add a small script to do so? Maybe done by a gh action as part of a release process?

2022-04-07 14:24 UTC, skgbafa approved these changes

2022-04-08 11:10 UTC, cobward commented
Linter and .nvmrc added. Will address the publishing of the docs in a future PR.

2022-04-08 11:11 UTC, merged